"""add idempotency_key to tasks

Revision ID: d6dd58a7fa28
Revises: e6ce36543398
Create Date: 2026-07-23 16:37:15.872927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6dd58a7fa28'
down_revision: Union[str, Sequence[str], None] = 'e6ce36543398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_tasks_key_idempotency', ['api_key_id', 'idempotency_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tasks_key_idempotency', type_='unique')
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
