"""initial_schema

Revision ID: d78676edc1c6
Revises: 
Create Date: 2026-07-22 12:18:33.852488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78676edc1c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_names', sa.JSON(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('file_total_bytes', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=50), nullable=False),
    sa.Column('parse_method', sa.String(length=50), nullable=True),
    sa.Column('lang_list', sa.JSON(), nullable=True),
    sa.Column('effort', sa.String(length=50), nullable=True),
    sa.Column('formula_enable', sa.Boolean(), nullable=True),
    sa.Column('table_enable', sa.Boolean(), nullable=True),
    sa.Column('image_analysis', sa.Boolean(), nullable=True),
    sa.Column('return_md', sa.Boolean(), nullable=True),
    sa.Column('return_middle_json', sa.Boolean(), nullable=True),
    sa.Column('return_model_output', sa.Boolean(), nullable=True),
    sa.Column('return_content_list', sa.Boolean(), nullable=True),
    sa.Column('return_images', sa.Boolean(), nullable=True),
    sa.Column('response_format_zip', sa.Boolean(), nullable=True),
    sa.Column('return_original_file', sa.Boolean(), nullable=True),
    sa.Column('client_side_output_generation', sa.Boolean(), nullable=True),
    sa.Column('server_url', sa.String(length=500), nullable=True),
    sa.Column('start_page_id', sa.Integer(), nullable=True),
    sa.Column('end_page_id', sa.Integer(), nullable=True),
    sa.Column('upstream_url', sa.String(length=500), nullable=False),
    sa.Column('upstream_task_id', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_poll_failures', sa.Integer(), nullable=False),
    sa.Column('queued_ahead', sa.Integer(), nullable=True),
    sa.Column('cache_dir', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('upstream_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_api_key_id'), 'tasks', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_key_status_created', 'tasks', ['api_key_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_upstream_task_id'), 'tasks', ['upstream_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_upstream_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('ix_tasks_key_status_created', table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_api_key_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
