"""add owner_id to api_keys

Revision ID: e6ce36543398
Revises: e795202aca0b
Create Date: 2026-07-22 16:29:46.192042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ce36543398'
down_revision: Union[str, Sequence[str], None] = 'e795202aca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_keys_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_api_keys_owner_id', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint('fk_api_keys_owner_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_api_keys_owner_id'))
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
